name: amberframework.org

server:
  host: 0.0.0.0
  port: 3000
  secret_key_base: amberframework-development

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  skip: []
  context:
    - request
    - session
    - headers
    - cookies
    - params
